### ISSUE TITLE
Cannot compile Wii controller example

### ISSUE THREAD

**Issue by Croccy22** [TwBurn/cdi-controller-library#1]
I may be missing something very obvious here but the example sketch tries to include <Wii.h>

What Library do I need to install to get this file? It doesn't appear to be in your code so I'm assuming it's an external library maybe?

I couldn't see it mentioned anywhere in your readme or Wiki.

Thanks, Matt.

**Comment by TwBurn** [comment]
​Hello Matt,

Have you installed the USB Host Shield Library? You can find it on https://github.com/felis/USB_Host_Shield_2.0 or install it via the Arduino IDE. The wii.h file is included in this library.

The readme doesn't specify it explicitly, I'll change that later.

Jeffrey

**Comment by Croccy22** [comment]
Hi, Yeah I worked it out a few minutes after I posted this lol. Typical.

Anyway my next stumbling block is I now have it fully compiling but the Arduino IDE says it is too big for the pro micro. Did you flash it the standard way with the Arduino bootloader or do you need to flash it with an avr programmer?

The message says something like the size is 30xxx bytes but the max size is 28xxx. I can't remember the exact values and I think I've currently toasted my pro micro so have another on its way :D.

**Comment by Croccy22** [comment]
Oh and I also needed to install the onetimer? library to get it to compile so may want to add that to the documentation :)

**Comment by TwBurn** [comment]
Right, that library is needed as well, I'll add that as well. I did not try the Wii example using the pro micro, but using the regular one, that uses less memory. Perhaps you can remove some print() statements to make the code smaller.

If your Pro Micro doesn't work, you can hook it up with USB to the computer, load up the "blink" example in the Arduino IDE, reset it two/three times fast (connect RESET and GROUND if I recall correctly) then directly press program in the Arduino IDE, that will unbrick the Pro Micro.

**Comment by TwBurn** [comment]
Which example are you loading? Except for the two player one they should be small enough. Though, most of the examples were developed using an Arduino Uno, which has a bit more memory than a Pro Micro.

Also, for code with the setup described on the wiki, you can get them from https://github.com/TwBurn/usb2cdi

Another important remark, if you want to use the Pro Micro standalone (not connected to a computer) make sure to remove all the Serial.* statements, else it'll freeze up.

**Comment by Croccy22** [comment]
I think my pro micro is beyond that. I tried to flash it via an isp programmer and overwrote the bootloader so I had access to the full 32k hoping that might work. But it didn't flash correctly and now isn't recognised by the PC due to no bootloader and it wont reflash as it says the identification of the chip is invalid lol.

I will try trimming down the code and see if I can get it small enough to flash to a new board.

Hoping eventually to try using the wii mote as the gun controller for games such as mad dog. Have you tried that yet?

Thanks for the project though, if I can get it all working its exactly what I am after. I will do a write up on my website too.

**Comment by Croccy22** [comment]
I was using the WiiController example

**Comment by Croccy22** [comment]
Ok, So I have just downloaded the WiiBT-1p from your link above. Loaded it into the Arduino IDE. I have already imported both the USB Host Shield 2 Library and the TimerOne Library. I select the board as Arduino Leonardo and hit compile.

I get the message: 

`Sketch uses 30358 bytes (105%) of program storage space. Maximum is 28672 bytes.

Global variables use 942 bytes (36%) of dynamic memory, leaving 1618 bytes for local variables. Maximum is 2560 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Arduino Leonardo.`

Which is pretty much identical to the results I get with the WiiController Example. I tried stripping the serial print lines out of it but it's still too big so I guess it's the libraries that are taking up the space rather than our sketch.

But I assume you must have got this to work with the "compact design" which is what I am trying to build? As that is using a Pro Micro?

**Comment by TwBurn** [comment]
That's weird, when I compile the WiiBT-1p I get:
```
Sketch uses 28084 bytes (97%) of program storage space. Maximum is 28672 bytes.
Global variables use 937 bytes (36%) of dynamic memory, leaving 1623 bytes for local variables. Maximum is 2560 bytes.
```
And yes, I get everything to work with the "compact design" - I've build quite a few of those so far. What versions of the Arduino IDE and libraries are you using?

About the gun controller, there is a WiiLightgun example, where it does exactly that. In that case you do need to edit something in the USB Host Shield Library files, in order to enable the IR sensor.

**Comment by Croccy22** [comment]
I'm using latest versions of everything.

So Arduino IDE is 1.8.15
USB host shield Library is 2.0 b651130 
TimerOne is version 1.1.0

Could you zip up your current version of the USB library and link me to it? Maybe the newest versions have got bigger with all the additional features they are adding? 

I have just tried building it all on a completely clean laptop and my build size is a bit smaller on this but I am still 1k too big :/

**Comment by TwBurn** [comment]
I've zipped all the libraries and attached them. 

My versions:
- Arduino IDE 1.8.13
- USB Host Shield 2.0 v1.3.2 (I think)
- TimerOne 1.1.0

[libraries.zip](https://github.com/TwBurn/cdi-controller-library/files/6626779/libraries.zip)

Using the Library manager you can install a different version. I tried 1.6.0 and that one was indeed too big.

**Comment by Croccy22** [comment]
That now compiles :)

So it looks like the USB Host Library has grown quite a bit in recent months. Just before you posted this zip, I downloaded a version from January and that just got it under the limit.

The version you have gives a few percent free so will stick with that one.

Going to make it fun for you documenting the build process now lol. 

Thanks for the help. Will try and get this all built tomorrow and stick it in a 3D printed case to tidy it all up.

**Comment by TwBurn** [comment]
I tried a few versions; 1.6.0 is too big, 1.5.0 and 1.4.0 work but are bigger. 1.3.2, which I used, seems to be the smallest. Given that there's support added for all kinds of devices, it's understandable that the main functions have grown a bit, unfortunately. Especially for Wii controllers, where you need the USB code, the Bluetooth code and the Wii code, which adds up fast.

I do have a Arduino Mega 2560 Pro lying around, I might be looking into that in the near future, would require some different wiring, and won't be as small/compact as the Pro Micro route (also probably can't solder everything up as a nice stack) but would allow for bigger programs.

If you do manage a nice 3D printed case, perhaps you would be so kind to share the files? I'm currently modifying small 50x35x20mm boxes, which give a nice fit as well.

**Comment by Croccy22** [comment]
Yep no problem. Once I've done a design I will link you to the STL so others can print it :)

**Comment by TwBurn** [comment]
I've added a small paragraph to the `readme.md`, mentioning the prerequisite libraries, and the preferred version for the USB Host Shield Library.

**Comment by Croccy22** [comment]
A couple more question for you today :)

I have built the hardware now but can't get the Wiimote to pair. So two questions, what BT dongle do you use with yours? And is there anything specific you need to do to pair when using the WiiBT-1p sketch? Should you just need to power the device via USB then put wiimote in pairing mode by pressing 1 and 2 together?

I currently don't have the device connected to the CDi as I was expecting to be able to pair without that connection in place to start with. Should that work?

I've looked on the supported dongle list for the USB host shield and the only one I can currently source on Amazon won't arrive until Monday, sad times :(

**Comment by TwBurn** [comment]
In order to pair you need to supply "PAIR" or "true" as an argument into the Wii object. You should be able to pair without having it connected to the CD-i. I've got a few generic Bluetooth dongles and they all work. As long as they support BT2+ I think they should work. If your bluetooth dongle has a LED in it, if that turns on you know it's supported, at least it's my experience the devices attached only power on properly if you have the right code loaded (be it a BT dongle, Magic NS dongle or USB mouse)

Now getting it to pair can be quite finicky, I generally have the most luck if I set the Wiimote to pair just before I power the device via USB. Sometimes you do need to press the red pair button.

**Comment by TwBurn** [comment]
Also, I don't know if you're on the CD-i discord, that might be a tad easier than "chat" using the issue tracker :)

https://discord.gg/TKPejTfw6D
